//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uruntakip.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblarizakategorileri
    {
        public int ariza_kategori_ID { get; set; }
        public Nullable<int> makinatipi { get; set; }
        public string kategoriadi { get; set; }
    }
}
