//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uruntakip.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblarizalar
    {
        public int arizaid { get; set; }
        public Nullable<int> makina_id { get; set; }
        public Nullable<int> kategori_id { get; set; }
        public string tanım { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<int> durum { get; set; }
    }
}
