//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uruntakip.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        public int firmaid { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string email { get; set; }
        public string telefon { get; set; }
        public string adres { get; set; }
        public string hesapno { get; set; }
        public string firmaadi { get; set; }
        public Nullable<int> musteritipi { get; set; }
    }
}
