//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uruntakip.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblgonerimtipleri
    {
        public int gonderiID { get; set; }
        public Nullable<int> sevkiyat_id { get; set; }
        public string gonderimadi { get; set; }
        public string aciklama { get; set; }
    }
}
