//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uruntakip.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbllogin
    {
        public int girisid { get; set; }
        public string eposta { get; set; }
        public string sifre { get; set; }
        public Nullable<int> durum { get; set; }
    }
}
