//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uruntakip.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblmakina
    {
        public int makinaid { get; set; }
        public string serino { get; set; }
        public int makinatip_id { get; set; }
        public Nullable<int> musteri_id { get; set; }
    }
}
