//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uruntakip.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblteklif
    {
        public int teklifid { get; set; }
        public Nullable<int> musteri_id { get; set; }
        public Nullable<System.DateTime> tekliftarihi { get; set; }
        public string acıklama { get; set; }
    }
}
