//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uruntakip.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblteklif_urunler
    {
        public int teklifurun_id { get; set; }
        public Nullable<int> teklif_id { get; set; }
        public Nullable<int> urun_id { get; set; }
        public string urunadi { get; set; }
        public Nullable<decimal> urunfiyati { get; set; }
        public Nullable<int> urunadeti { get; set; }
        public Nullable<decimal> kdv { get; set; }
    }
}
