//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uruntakip.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblteklifsevkdetayı
    {
        public int teklifdetayid { get; set; }
        public Nullable<int> teklif_id { get; set; }
        public string sevkadresi { get; set; }
        public Nullable<int> sevkiyattipi { get; set; }
        public Nullable<int> odemetipi { get; set; }
        public Nullable<int> iskonto { get; set; }
        public Nullable<int> teslimattipi { get; set; }
        public string makinano { get; set; }
        public string arizano { get; set; }
    }
}
