//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uruntakip.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltedarikci
    {
        public int tedarikciID { get; set; }
        public string tedarikciismi { get; set; }
        public string telefon { get; set; }
        public string email { get; set; }
        public string adress { get; set; }
    }
}
