//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uruntakip.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblteklif
    {
        public int teklifid { get; set; }
        public Nullable<int> musteri_id { get; set; }
        public string teklifno { get; set; }
        public Nullable<int> teslimatid { get; set; }
        public string teslimat_notu { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public string teklifnotu { get; set; }
        public Nullable<int> sevkiyat_id { get; set; }
        public string makinserino { get; set; }
        public string arizano { get; set; }
        public Nullable<int> iskonto { get; set; }
        public Nullable<int> parabirimi { get; set; }
        public string gdr_adres { get; set; }
        public string gdr_email { get; set; }
        public Nullable<int> durum { get; set; }
    }
}
