//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uruntakip.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblurun_islem_Gecmisi
    {
        public int islem_id { get; set; }
        public Nullable<int> urun_detay_id { get; set; }
        public Nullable<int> uruneskimusteri { get; set; }
        public Nullable<int> urunyenimusteri { get; set; }
        public Nullable<System.DateTime> islem_tarihi { get; set; }
        public Nullable<int> islemtipi { get; set; }
        public Nullable<int> makina_id { get; set; }
    }
}
