//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uruntakip.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblurunler
    {
        public int uruid { get; set; }
        public Nullable<int> urunkategori { get; set; }
        public Nullable<decimal> alisfiyati { get; set; }
        public Nullable<decimal> satiscarpanı { get; set; }
        public Nullable<int> stok { get; set; }
        public string stokadi { get; set; }
    }
}
